### ISSUE TITLE
Further development of the website

### ISSUE THREAD

**Issue by cesa-vit** [cesa-vit/Hacktoberfest-2023#1]
Help is needed to complete the website

**Comment by KalashJain591** [comment]
Hello ,
Can You Post the exact requirement

**Comment by elite-fable** [comment]
i want to contribute ,please assign me this project work.

**Comment by SayaliMarathe-13** [comment]
Hello sir,
I am relatively new to the open source and willing to contribute in this repository, can you please assign this to me
