### ISSUE TITLE
Scroll bar appears when the logo or image is hovered.

### ISSUE THREAD

**Issue by cesa-vit** [cesa-vit/Hacktoberfest-2023#5]
Scroll bar appears when the logo or image is hovered. The name of the logo or image is archcraft, the image has no name but it's placed under a " div " named photo. Do whatever is needed to REMOVE the scroll bar which appears when the image or logo is hovered but hovering effect SHOULD be RETAINED. The " div " which contains the logo or image may have been centered using naive approach, if you can then use more professional or feasible approach to center this div.

**Comment by pkd019** [comment]
I want to work on it.

**Comment by Ahnaf-codes** [comment]
@cesa-vit I can help you with this issue. So please assign me
